/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountId = bigint;
export type AccountType = { 'revenue' : null } |
  { 'liability' : null } |
  { 'expense' : null } |
  { 'asset' : null } |
  { 'equity' : null };
export interface AuditLog {
  'id' : AuditLogId,
  'action' : string,
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export type AuditLogId = bigint;
export interface BalanceSheet {
  'month' : bigint,
  'liabilities' : Array<BalanceSheetLine>,
  'totalAssets' : bigint,
  'totalLiabilities' : bigint,
  'assets' : Array<BalanceSheetLine>,
  'year' : bigint,
  'totalEquity' : bigint,
  'equity' : Array<BalanceSheetLine>,
}
export interface BalanceSheetLine {
  'total' : bigint,
  'accountCode' : string,
  'accountName' : string,
}
export type BusinessRole = { 'accountant' : null } |
  { 'client' : null } |
  { 'admin' : null };
export interface CashFlow {
  'inflows' : Array<CashFlowLine>,
  'month' : bigint,
  'outflows' : Array<CashFlowLine>,
  'year' : bigint,
  'totalOutflows' : bigint,
  'netCashFlow' : bigint,
  'totalInflows' : bigint,
}
export interface CashFlowLine { 'value' : bigint, 'description' : string }
export interface ChartAccount {
  'id' : AccountId,
  'active' : boolean,
  'code' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'accountType' : AccountType,
  'parentCode' : [] | [string],
}
export interface Client {
  'id' : ClientId,
  'active' : boolean,
  'cnpj' : string,
  'name' : string,
  'createdAt' : Time,
  'plan' : PlanType,
  'walletType' : [] | [WalletType],
  'email' : string,
  'updatedAt' : Time,
  'address' : string,
  'bitcoinAddress' : [] | [string],
  'phone' : string,
}
export interface ClientBitcoinAddressResult {
  'walletType' : WalletType,
  'address' : string,
}
export type ClientId = bigint;
export interface ImportRecord {
  'id' : bigint,
  'importedAt' : Time,
  'importedBy' : Principal,
  'filename' : string,
  'recordCount' : bigint,
}
export interface IncomeStatement {
  'month' : bigint,
  'expenses' : Array<IncomeStatementLine>,
  'year' : bigint,
  'totalExpenses' : bigint,
  'revenues' : Array<IncomeStatementLine>,
  'totalRevenue' : bigint,
  'netIncome' : bigint,
}
export interface IncomeStatementLine {
  'total' : bigint,
  'accountCode' : string,
  'accountName' : string,
}
export interface JournalEntry {
  'id' : JournalEntryId,
  'clientId' : ClientId,
  'value' : bigint,
  'date' : Time,
  'createdAt' : Time,
  'createdBy' : Principal,
  'reference' : [] | [string],
  'description' : string,
  'debitAccountCode' : string,
  'creditAccountCode' : string,
}
export type JournalEntryId = bigint;
export type PlanType = { 'enterprise' : null } |
  { 'professional' : null } |
  { 'basic' : null };
export interface Subscription {
  'id' : SubscriptionId,
  'status' : SubscriptionStatus,
  'clientId' : ClientId,
  'createdAt' : Time,
  'plan' : PlanType,
  'updatedAt' : Time,
  'startDate' : Time,
}
export type SubscriptionId = bigint;
export type SubscriptionStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'suspended' : null };
export type Time = bigint;
export interface Transaction {
  'id' : TransactionId,
  'clientId' : ClientId,
  'transactionType' : TransactionType,
  'value' : bigint,
  'date' : Time,
  'hash' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'category' : TransactionCategory,
  'confirmed' : boolean,
}
export type TransactionCategory = { 'revenue' : null } |
  { 'liability' : null } |
  { 'expense' : null } |
  { 'asset' : null } |
  { 'equity' : null };
export type TransactionId = bigint;
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface UserProfile {
  'clientId' : [] | [ClientId],
  'cnpj' : [] | [string],
  'name' : string,
  'businessRole' : BusinessRole,
  'companyEmail' : [] | [string],
  'responsibleName' : [] | [string],
  'email' : string,
  'demoMode' : [] | [boolean],
  'companyWallet' : [] | [string],
  'segment' : [] | [string],
  'companyName' : [] | [string],
  'companyPhone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WalletType = { 'ckbtc' : null } |
  { 'manual' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChartAccount' : ActorMethod<[ChartAccount], AccountId>,
  'addJournalEntry' : ActorMethod<[JournalEntry], JournalEntryId>,
  'addSubscription' : ActorMethod<[Subscription], SubscriptionId>,
  'addTransaction' : ActorMethod<[Transaction], TransactionId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChartAccount' : ActorMethod<[AccountId], undefined>,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'editChartAccount' : ActorMethod<[AccountId, ChartAccount], undefined>,
  'editClient' : ActorMethod<[ClientId, Client], undefined>,
  'generateCkBtcAddress' : ActorMethod<[ClientId], string>,
  'getAllAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getAllChartAccounts' : ActorMethod<[], Array<ChartAccount>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBalanceSheet' : ActorMethod<[ClientId, bigint, bigint], BalanceSheet>,
  'getCallerDemoMode' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashFlow' : ActorMethod<[ClientId, bigint, bigint], CashFlow>,
  'getChartAccount' : ActorMethod<[AccountId], [] | [ChartAccount]>,
  'getCkBtcBalance' : ActorMethod<[ClientId], bigint>,
  'getClient' : ActorMethod<[ClientId], [] | [Client]>,
  'getClientBitcoinAddress' : ActorMethod<
    [ClientId],
    [] | [ClientBitcoinAddressResult]
  >,
  'getImportHistory' : ActorMethod<[], Array<ImportRecord>>,
  'getIncomeStatement' : ActorMethod<
    [ClientId, bigint, bigint],
    IncomeStatement
  >,
  'getJournalEntriesByClientId' : ActorMethod<[ClientId], Array<JournalEntry>>,
  'getSubscriptionByClientId' : ActorMethod<[ClientId], [] | [Subscription]>,
  'getTransactionsByClientId' : ActorMethod<[ClientId], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importTransactions' : ActorMethod<
    [Array<Transaction>, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerClient' : ActorMethod<[Client], ClientId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompanyProfile' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'setCallerDemoMode' : ActorMethod<[boolean], undefined>,
  'setClientBitcoinAddress' : ActorMethod<
    [ClientId, string, WalletType],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];