/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientId = IDL.Nat;
export const Time = IDL.Int;
export const PlanType = IDL.Variant({
  'enterprise' : IDL.Null,
  'professional' : IDL.Null,
  'basic' : IDL.Null,
});
export const WalletType = IDL.Variant({
  'ckbtc' : IDL.Null,
  'manual' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : ClientId,
  'active' : IDL.Bool,
  'cnpj' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'plan' : PlanType,
  'walletType' : IDL.Opt(WalletType),
  'email' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'bitcoinAddress' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const BusinessRole = IDL.Variant({
  'accountant' : IDL.Null,
  'client' : IDL.Null,
  'admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'clientId' : IDL.Opt(ClientId),
  'name' : IDL.Text,
  'businessRole' : BusinessRole,
  'email' : IDL.Text,
});
export const ClientBitcoinAddressResult = IDL.Record({
  'walletType' : WalletType,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'editClient' : IDL.Func([ClientId, Client], [], []),
  'generateCkBtcAddress' : IDL.Func([ClientId], [IDL.Text], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCkBtcBalance' : IDL.Func([ClientId], [IDL.Nat], []),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getClientBitcoinAddress' : IDL.Func(
      [ClientId],
      [IDL.Opt(ClientBitcoinAddressResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerClient' : IDL.Func([Client], [ClientId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setClientBitcoinAddress' : IDL.Func(
      [ClientId, IDL.Text, WalletType],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientId = IDL.Nat;
  const Time = IDL.Int;
  const PlanType = IDL.Variant({
    'enterprise' : IDL.Null,
    'professional' : IDL.Null,
    'basic' : IDL.Null,
  });
  const WalletType = IDL.Variant({ 'ckbtc' : IDL.Null, 'manual' : IDL.Null });
  const Client = IDL.Record({
    'id' : ClientId,
    'active' : IDL.Bool,
    'cnpj' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'plan' : PlanType,
    'walletType' : IDL.Opt(WalletType),
    'email' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'bitcoinAddress' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const BusinessRole = IDL.Variant({
    'accountant' : IDL.Null,
    'client' : IDL.Null,
    'admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'clientId' : IDL.Opt(ClientId),
    'name' : IDL.Text,
    'businessRole' : BusinessRole,
    'email' : IDL.Text,
  });
  const ClientBitcoinAddressResult = IDL.Record({
    'walletType' : WalletType,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'editClient' : IDL.Func([ClientId, Client], [], []),
    'generateCkBtcAddress' : IDL.Func([ClientId], [IDL.Text], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCkBtcBalance' : IDL.Func([ClientId], [IDL.Nat], []),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getClientBitcoinAddress' : IDL.Func(
        [ClientId],
        [IDL.Opt(ClientBitcoinAddressResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerClient' : IDL.Func([Client], [ClientId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setClientBitcoinAddress' : IDL.Func(
        [ClientId, IDL.Text, WalletType],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };