/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IncomeStatement {
    month: bigint;
    expenses: Array<IncomeStatementLine>;
    year: bigint;
    totalExpenses: bigint;
    revenues: Array<IncomeStatementLine>;
    totalRevenue: bigint;
    netIncome: bigint;
}
export interface AuditLog {
    id: AuditLogId;
    action: string;
    user: Principal;
    timestamp: Time;
    details: string;
}
export type Time = bigint;
export interface CashFlow {
    inflows: Array<CashFlowLine>;
    month: bigint;
    outflows: Array<CashFlowLine>;
    year: bigint;
    totalOutflows: bigint;
    netCashFlow: bigint;
    totalInflows: bigint;
}
export type AuditLogId = bigint;
export interface Transaction {
    id: TransactionId;
    clientId: ClientId;
    transactionType: TransactionType;
    value: bigint;
    date: Time;
    hash: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    category: TransactionCategory;
    confirmed: boolean;
}
export interface Subscription {
    id: SubscriptionId;
    status: SubscriptionStatus;
    clientId: ClientId;
    createdAt: Time;
    plan: PlanType;
    updatedAt: Time;
    startDate: Time;
}
export type SubscriptionId = bigint;
export type TransactionId = bigint;
export type AccountId = bigint;
export interface IncomeStatementLine {
    total: bigint;
    accountCode: string;
    accountName: string;
}
export interface BalanceSheetLine {
    total: bigint;
    accountCode: string;
    accountName: string;
}
export interface Client {
    id: ClientId;
    active: boolean;
    cnpj: string;
    name: string;
    createdAt: Time;
    plan: PlanType;
    walletType?: WalletType;
    email: string;
    updatedAt: Time;
    address: string;
    bitcoinAddress?: string;
    phone: string;
}
export interface ClientBitcoinAddressResult {
    walletType: WalletType;
    address: string;
}
export type ClientId = bigint;
export interface ChartAccount {
    id: AccountId;
    active: boolean;
    code: string;
    name: string;
    createdAt: Time;
    description: string;
    accountType: AccountType;
    parentCode?: string;
}
export interface CashFlowLine {
    value: bigint;
    description: string;
}
export type JournalEntryId = bigint;
export interface ImportRecord {
    id: bigint;
    importedAt: Time;
    importedBy: Principal;
    filename: string;
    recordCount: bigint;
}
export interface JournalEntry {
    id: JournalEntryId;
    clientId: ClientId;
    value: bigint;
    date: Time;
    createdAt: Time;
    createdBy: Principal;
    reference?: string;
    description: string;
    debitAccountCode: string;
    creditAccountCode: string;
}
export interface BalanceSheet {
    month: bigint;
    liabilities: Array<BalanceSheetLine>;
    totalAssets: bigint;
    totalLiabilities: bigint;
    assets: Array<BalanceSheetLine>;
    year: bigint;
    totalEquity: bigint;
    equity: Array<BalanceSheetLine>;
}
export interface UserProfile {
    clientId?: ClientId;
    cnpj?: string;
    name: string;
    businessRole: BusinessRole;
    companyEmail?: string;
    responsibleName?: string;
    email: string;
    demoMode?: boolean;
    companyWallet?: string;
    segment?: string;
    companyName?: string;
    companyPhone?: string;
}
export enum AccountType {
    revenue = "revenue",
    liability = "liability",
    expense = "expense",
    asset = "asset",
    equity = "equity"
}
export enum BusinessRole {
    accountant = "accountant",
    client = "client",
    admin = "admin"
}
export enum PlanType {
    enterprise = "enterprise",
    professional = "professional",
    basic = "basic"
}
export enum SubscriptionStatus {
    active = "active",
    inactive = "inactive",
    suspended = "suspended"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WalletType {
    ckbtc = "ckbtc",
    manual = "manual"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAuthorizedEmail(email: string): Promise<void>;
    addChartAccount(account: ChartAccount): Promise<AccountId>;
    addJournalEntry(entry: JournalEntry): Promise<JournalEntryId>;
    addSubscription(newSub: Subscription): Promise<SubscriptionId>;
    addTransaction(newTx: Transaction): Promise<TransactionId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteChartAccount(accountId: AccountId): Promise<void>;
    deleteClient(clientId: ClientId): Promise<void>;
    editChartAccount(accountId: AccountId, updated: ChartAccount): Promise<void>;
    editClient(clientId: ClientId, updatedClient: Client): Promise<void>;
    generateCkBtcAddress(clientId: ClientId): Promise<string>;
    getAllAuditLogs(): Promise<Array<AuditLog>>;
    getAllChartAccounts(): Promise<Array<ChartAccount>>;
    getAllClients(): Promise<Array<Client>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAuthorizedEmails(): Promise<Array<string>>;
    getBalanceSheet(clientId: ClientId, month: bigint, year: bigint): Promise<BalanceSheet>;
    getCallerDemoMode(): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCashFlow(clientId: ClientId, month: bigint, year: bigint): Promise<CashFlow>;
    getChartAccount(accountId: AccountId): Promise<ChartAccount | null>;
    getCkBtcBalance(clientId: ClientId): Promise<bigint>;
    getClient(clientId: ClientId): Promise<Client | null>;
    getClientBitcoinAddress(clientId: ClientId): Promise<ClientBitcoinAddressResult | null>;
    getImportHistory(): Promise<Array<ImportRecord>>;
    getIncomeStatement(clientId: ClientId, month: bigint, year: bigint): Promise<IncomeStatement>;
    getJournalEntriesByClientId(clientId: ClientId): Promise<Array<JournalEntry>>;
    getSubscriptionByClientId(clientId: ClientId): Promise<Subscription | null>;
    getTransactionsByClientId(clientId: ClientId): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importTransactions(txs: Array<Transaction>, filename: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isEmailAuthorized(email: string): Promise<boolean>;
    registerClient(newClient: Client): Promise<ClientId>;
    removeAuthorizedEmail(email: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCompanyProfile(companyName: string, cnpj: string, segment: string, responsibleName: string, companyEmail: string, companyPhone: string, companyWallet: string): Promise<void>;
    setCallerDemoMode(demoMode: boolean): Promise<void>;
    setClientBitcoinAddress(clientId: ClientId, address: string, walletType: WalletType): Promise<void>;
}
import type { AccountId as _AccountId, AccountType as _AccountType, BusinessRole as _BusinessRole, ChartAccount as _ChartAccount, Client as _Client, ClientBitcoinAddressResult as _ClientBitcoinAddressResult, ClientId as _ClientId, JournalEntry as _JournalEntry, JournalEntryId as _JournalEntryId, PlanType as _PlanType, Subscription as _Subscription, SubscriptionId as _SubscriptionId, SubscriptionStatus as _SubscriptionStatus, Time as _Time, Transaction as _Transaction, TransactionCategory as _TransactionCategory, TransactionId as _TransactionId, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, WalletType as _WalletType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAuthorizedEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuthorizedEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuthorizedEmail(arg0);
            return result;
        }
    }
    async addChartAccount(arg0: ChartAccount): Promise<AccountId> {
        if (this.processError) {
            try {
                const result = await this.actor.addChartAccount(to_candid_ChartAccount_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChartAccount(to_candid_ChartAccount_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addJournalEntry(arg0: JournalEntry): Promise<JournalEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(to_candid_JournalEntry_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(to_candid_JournalEntry_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSubscription(arg0: Subscription): Promise<SubscriptionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubscription(to_candid_Subscription_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubscription(to_candid_Subscription_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<TransactionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteChartAccount(arg0: AccountId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChartAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChartAccount(arg0);
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async editChartAccount(arg0: AccountId, arg1: ChartAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editChartAccount(arg0, to_candid_ChartAccount_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editChartAccount(arg0, to_candid_ChartAccount_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async editClient(arg0: ClientId, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editClient(arg0, to_candid_Client_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editClient(arg0, to_candid_Client_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateCkBtcAddress(arg0: ClientId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCkBtcAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCkBtcAddress(arg0);
            return result;
        }
    }
    async getAllAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAuditLogs();
            return result;
        }
    }
    async getAllChartAccounts(): Promise<Array<ChartAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChartAccounts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChartAccounts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthorizedEmails(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthorizedEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthorizedEmails();
            return result;
        }
    }
    async getBalanceSheet(arg0: ClientId, arg1: bigint, arg2: bigint): Promise<BalanceSheet> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalanceSheet(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalanceSheet(arg0, arg1, arg2);
            return result;
        }
    }
    async getCallerDemoMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDemoMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDemoMode();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashFlow(arg0: ClientId, arg1: bigint, arg2: bigint): Promise<CashFlow> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashFlow(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashFlow(arg0, arg1, arg2);
            return result;
        }
    }
    async getChartAccount(arg0: AccountId): Promise<ChartAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChartAccount(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChartAccount(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCkBtcBalance(arg0: ClientId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCkBtcBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCkBtcBalance(arg0);
            return result;
        }
    }
    async getClient(arg0: ClientId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientBitcoinAddress(arg0: ClientId): Promise<ClientBitcoinAddressResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientBitcoinAddress(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientBitcoinAddress(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImportHistory(): Promise<Array<ImportRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportHistory();
            return result;
        }
    }
    async getIncomeStatement(arg0: ClientId, arg1: bigint, arg2: bigint): Promise<IncomeStatement> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeStatement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeStatement(arg0, arg1, arg2);
            return result;
        }
    }
    async getJournalEntriesByClientId(arg0: ClientId): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntriesByClientId(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntriesByClientId(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionByClientId(arg0: ClientId): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionByClientId(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionByClientId(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByClientId(arg0: ClientId): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByClientId(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByClientId(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async importTransactions(arg0: Array<Transaction>, arg1: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.importTransactions(to_candid_vec_n67(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importTransactions(to_candid_vec_n67(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEmailAuthorized(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEmailAuthorized(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEmailAuthorized(arg0);
            return result;
        }
    }
    async registerClient(arg0: Client): Promise<ClientId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerClient(to_candid_Client_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerClient(to_candid_Client_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removeAuthorizedEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAuthorizedEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAuthorizedEmail(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCompanyProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompanyProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompanyProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async setCallerDemoMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCallerDemoMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCallerDemoMode(arg0);
            return result;
        }
    }
    async setClientBitcoinAddress(arg0: ClientId, arg1: string, arg2: WalletType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setClientBitcoinAddress(arg0, arg1, to_candid_WalletType_n22(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClientBitcoinAddress(arg0, arg1, to_candid_WalletType_n22(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_AccountType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessRole): BusinessRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_ChartAccount_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartAccount): ChartAccount {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ClientBitcoinAddressResult_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientBitcoinAddressResult): ClientBitcoinAddressResult {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_JournalEntry_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): JournalEntry {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionCategory_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionCategory): TransactionCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_WalletType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletType): WalletType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletType]): WalletType | null {
    return value.length === 0 ? null : from_candid_WalletType_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientId]): ClientId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChartAccount]): ChartAccount | null {
    return value.length === 0 ? null : from_candid_ChartAccount_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientBitcoinAddressResult]): ClientBitcoinAddressResult | null {
    return value.length === 0 ? null : from_candid_ClientBitcoinAddressResult_n64(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AccountId;
    active: boolean;
    code: string;
    name: string;
    createdAt: _Time;
    description: string;
    accountType: _AccountType;
    parentCode: [] | [string];
}): {
    id: AccountId;
    active: boolean;
    code: string;
    name: string;
    createdAt: Time;
    description: string;
    accountType: AccountType;
    parentCode?: string;
} {
    return {
        id: value.id,
        active: value.active,
        code: value.code,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        accountType: from_candid_AccountType_n27(_uploadFile, _downloadFile, value.accountType),
        parentCode: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.parentCode))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    active: boolean;
    cnpj: string;
    name: string;
    createdAt: _Time;
    plan: _PlanType;
    walletType: [] | [_WalletType];
    email: string;
    updatedAt: _Time;
    address: string;
    bitcoinAddress: [] | [string];
    phone: string;
}): {
    id: ClientId;
    active: boolean;
    cnpj: string;
    name: string;
    createdAt: Time;
    plan: PlanType;
    walletType?: WalletType;
    email: string;
    updatedAt: Time;
    address: string;
    bitcoinAddress?: string;
    phone: string;
} {
    return {
        id: value.id,
        active: value.active,
        cnpj: value.cnpj,
        name: value.name,
        createdAt: value.createdAt,
        plan: from_candid_PlanType_n33(_uploadFile, _downloadFile, value.plan),
        walletType: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.walletType)),
        email: value.email,
        updatedAt: value.updatedAt,
        address: value.address,
        bitcoinAddress: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.bitcoinAddress)),
        phone: value.phone
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JournalEntryId;
    clientId: _ClientId;
    value: bigint;
    date: _Time;
    createdAt: _Time;
    createdBy: Principal;
    reference: [] | [string];
    description: string;
    debitAccountCode: string;
    creditAccountCode: string;
}): {
    id: JournalEntryId;
    clientId: ClientId;
    value: bigint;
    date: Time;
    createdAt: Time;
    createdBy: Principal;
    reference?: string;
    description: string;
    debitAccountCode: string;
    creditAccountCode: string;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        value: value.value,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        reference: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.reference)),
        description: value.description,
        debitAccountCode: value.debitAccountCode,
        creditAccountCode: value.creditAccountCode
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubscriptionId;
    status: _SubscriptionStatus;
    clientId: _ClientId;
    createdAt: _Time;
    plan: _PlanType;
    updatedAt: _Time;
    startDate: _Time;
}): {
    id: SubscriptionId;
    status: SubscriptionStatus;
    clientId: ClientId;
    createdAt: Time;
    plan: PlanType;
    updatedAt: Time;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_SubscriptionStatus_n44(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        createdAt: value.createdAt,
        plan: from_candid_PlanType_n33(_uploadFile, _downloadFile, value.plan),
        updatedAt: value.updatedAt,
        startDate: value.startDate
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    clientId: _ClientId;
    transactionType: _TransactionType;
    value: bigint;
    date: _Time;
    hash: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    category: _TransactionCategory;
    confirmed: boolean;
}): {
    id: TransactionId;
    clientId: ClientId;
    transactionType: TransactionType;
    value: bigint;
    date: Time;
    hash: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    category: TransactionCategory;
    confirmed: boolean;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        transactionType: from_candid_TransactionType_n49(_uploadFile, _downloadFile, value.transactionType),
        value: value.value,
        date: value.date,
        hash: value.hash,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: from_candid_TransactionCategory_n51(_uploadFile, _downloadFile, value.category),
        confirmed: value.confirmed
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientId: [] | [_ClientId];
    cnpj: [] | [string];
    name: string;
    businessRole: _BusinessRole;
    companyEmail: [] | [string];
    responsibleName: [] | [string];
    email: string;
    demoMode: [] | [boolean];
    companyWallet: [] | [string];
    segment: [] | [string];
    companyName: [] | [string];
    companyPhone: [] | [string];
}): {
    clientId?: ClientId;
    cnpj?: string;
    name: string;
    businessRole: BusinessRole;
    companyEmail?: string;
    responsibleName?: string;
    email: string;
    demoMode?: boolean;
    companyWallet?: string;
    segment?: string;
    companyName?: string;
    companyPhone?: string;
} {
    return {
        clientId: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.clientId)),
        cnpj: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.cnpj)),
        name: value.name,
        businessRole: from_candid_BusinessRole_n56(_uploadFile, _downloadFile, value.businessRole),
        companyEmail: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.companyEmail)),
        responsibleName: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.responsibleName)),
        email: value.email,
        demoMode: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.demoMode)),
        companyWallet: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.companyWallet)),
        segment: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.segment)),
        companyName: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.companyName)),
        companyPhone: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.companyPhone))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walletType: _WalletType;
    address: string;
}): {
    walletType: WalletType;
    address: string;
} {
    return {
        walletType: from_candid_WalletType_n36(_uploadFile, _downloadFile, value.walletType),
        address: value.address
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revenue: null;
} | {
    liability: null;
} | {
    expense: null;
} | {
    asset: null;
} | {
    equity: null;
}): AccountType {
    return "revenue" in value ? AccountType.revenue : "liability" in value ? AccountType.liability : "expense" in value ? AccountType.expense : "asset" in value ? AccountType.asset : "equity" in value ? AccountType.equity : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enterprise: null;
} | {
    professional: null;
} | {
    basic: null;
}): PlanType {
    return "enterprise" in value ? PlanType.enterprise : "professional" in value ? PlanType.professional : "basic" in value ? PlanType.basic : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ckbtc: null;
} | {
    manual: null;
}): WalletType {
    return "ckbtc" in value ? WalletType.ckbtc : "manual" in value ? WalletType.manual : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    suspended: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "inactive" in value ? SubscriptionStatus.inactive : "suspended" in value ? SubscriptionStatus.suspended : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountant: null;
} | {
    client: null;
} | {
    admin: null;
}): BusinessRole {
    return "accountant" in value ? BusinessRole.accountant : "client" in value ? BusinessRole.client : "admin" in value ? BusinessRole.admin : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChartAccount>): Array<ChartAccount> {
    return value.map((x)=>from_candid_ChartAccount_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Array<JournalEntry> {
    return value.map((x)=>from_candid_JournalEntry_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n47(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessRole_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessRole): _BusinessRole {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_ChartAccount_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartAccount): _ChartAccount {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Client_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Client): _Client {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_JournalEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalEntry): _JournalEntry {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Subscription_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subscription): _Subscription {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): _TransactionCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_WalletType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletType): _WalletType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TransactionId;
    clientId: ClientId;
    transactionType: TransactionType;
    value: bigint;
    date: Time;
    hash: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    category: TransactionCategory;
    confirmed: boolean;
}): {
    id: _TransactionId;
    clientId: _ClientId;
    transactionType: _TransactionType;
    value: bigint;
    date: _Time;
    hash: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    category: _TransactionCategory;
    confirmed: boolean;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        transactionType: to_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        value: value.value,
        date: value.date,
        hash: value.hash,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: to_candid_TransactionCategory_n17(_uploadFile, _downloadFile, value.category),
        confirmed: value.confirmed
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AccountId;
    active: boolean;
    code: string;
    name: string;
    createdAt: Time;
    description: string;
    accountType: AccountType;
    parentCode?: string;
}): {
    id: _AccountId;
    active: boolean;
    code: string;
    name: string;
    createdAt: _Time;
    description: string;
    accountType: _AccountType;
    parentCode: [] | [string];
} {
    return {
        id: value.id,
        active: value.active,
        code: value.code,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        accountType: to_candid_AccountType_n3(_uploadFile, _downloadFile, value.accountType),
        parentCode: value.parentCode ? candid_some(value.parentCode) : candid_none()
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ClientId;
    active: boolean;
    cnpj: string;
    name: string;
    createdAt: Time;
    plan: PlanType;
    walletType?: WalletType;
    email: string;
    updatedAt: Time;
    address: string;
    bitcoinAddress?: string;
    phone: string;
}): {
    id: _ClientId;
    active: boolean;
    cnpj: string;
    name: string;
    createdAt: _Time;
    plan: _PlanType;
    walletType: [] | [_WalletType];
    email: string;
    updatedAt: _Time;
    address: string;
    bitcoinAddress: [] | [string];
    phone: string;
} {
    return {
        id: value.id,
        active: value.active,
        cnpj: value.cnpj,
        name: value.name,
        createdAt: value.createdAt,
        plan: to_candid_PlanType_n11(_uploadFile, _downloadFile, value.plan),
        walletType: value.walletType ? candid_some(to_candid_WalletType_n22(_uploadFile, _downloadFile, value.walletType)) : candid_none(),
        email: value.email,
        updatedAt: value.updatedAt,
        address: value.address,
        bitcoinAddress: value.bitcoinAddress ? candid_some(value.bitcoinAddress) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JournalEntryId;
    clientId: ClientId;
    value: bigint;
    date: Time;
    createdAt: Time;
    createdBy: Principal;
    reference?: string;
    description: string;
    debitAccountCode: string;
    creditAccountCode: string;
}): {
    id: _JournalEntryId;
    clientId: _ClientId;
    value: bigint;
    date: _Time;
    createdAt: _Time;
    createdBy: Principal;
    reference: [] | [string];
    description: string;
    debitAccountCode: string;
    creditAccountCode: string;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        value: value.value,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        description: value.description,
        debitAccountCode: value.debitAccountCode,
        creditAccountCode: value.creditAccountCode
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientId?: ClientId;
    cnpj?: string;
    name: string;
    businessRole: BusinessRole;
    companyEmail?: string;
    responsibleName?: string;
    email: string;
    demoMode?: boolean;
    companyWallet?: string;
    segment?: string;
    companyName?: string;
    companyPhone?: string;
}): {
    clientId: [] | [_ClientId];
    cnpj: [] | [string];
    name: string;
    businessRole: _BusinessRole;
    companyEmail: [] | [string];
    responsibleName: [] | [string];
    email: string;
    demoMode: [] | [boolean];
    companyWallet: [] | [string];
    segment: [] | [string];
    companyName: [] | [string];
    companyPhone: [] | [string];
} {
    return {
        clientId: value.clientId ? candid_some(value.clientId) : candid_none(),
        cnpj: value.cnpj ? candid_some(value.cnpj) : candid_none(),
        name: value.name,
        businessRole: to_candid_BusinessRole_n71(_uploadFile, _downloadFile, value.businessRole),
        companyEmail: value.companyEmail ? candid_some(value.companyEmail) : candid_none(),
        responsibleName: value.responsibleName ? candid_some(value.responsibleName) : candid_none(),
        email: value.email,
        demoMode: value.demoMode ? candid_some(value.demoMode) : candid_none(),
        companyWallet: value.companyWallet ? candid_some(value.companyWallet) : candid_none(),
        segment: value.segment ? candid_some(value.segment) : candid_none(),
        companyName: value.companyName ? candid_some(value.companyName) : candid_none(),
        companyPhone: value.companyPhone ? candid_some(value.companyPhone) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: SubscriptionId;
    status: SubscriptionStatus;
    clientId: ClientId;
    createdAt: Time;
    plan: PlanType;
    updatedAt: Time;
    startDate: Time;
}): {
    id: _SubscriptionId;
    status: _SubscriptionStatus;
    clientId: _ClientId;
    createdAt: _Time;
    plan: _PlanType;
    updatedAt: _Time;
    startDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_SubscriptionStatus_n9(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        createdAt: value.createdAt,
        plan: to_candid_PlanType_n11(_uploadFile, _downloadFile, value.plan),
        updatedAt: value.updatedAt,
        startDate: value.startDate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    inactive: null;
} | {
    suspended: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.inactive ? {
        inactive: null
    } : value == SubscriptionStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    enterprise: null;
} | {
    professional: null;
} | {
    basic: null;
} {
    return value == PlanType.enterprise ? {
        enterprise: null
    } : value == PlanType.professional ? {
        professional: null
    } : value == PlanType.basic ? {
        basic: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletType): {
    ckbtc: null;
} | {
    manual: null;
} {
    return value == WalletType.ckbtc ? {
        ckbtc: null
    } : value == WalletType.manual ? {
        manual: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    revenue: null;
} | {
    liability: null;
} | {
    expense: null;
} | {
    asset: null;
} | {
    equity: null;
} {
    return value == AccountType.revenue ? {
        revenue: null
    } : value == AccountType.liability ? {
        liability: null
    } : value == AccountType.expense ? {
        expense: null
    } : value == AccountType.asset ? {
        asset: null
    } : value == AccountType.equity ? {
        equity: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessRole): {
    accountant: null;
} | {
    client: null;
} | {
    admin: null;
} {
    return value == BusinessRole.accountant ? {
        accountant: null
    } : value == BusinessRole.client ? {
        client: null
    } : value == BusinessRole.admin ? {
        admin: null
    } : value;
}
function to_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Transaction>): Array<_Transaction> {
    return value.map((x)=>to_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
